### ISSUE TITLE
[Quest] Bloody Breakout

### ISSUE THREAD

**Issue by kelsul** [Stormforge-gg/Bugtracker-Wotlk-Beta#18] opened 2022-04-08 08:53 UTC
**Description**: When Koltira Deathweaver exits the keep for Bloody Breakout, he mounts up and after taking a hit dismounts but continues to run at mounted speed. 

**Current behaviour**: Koltira Deathweaver dismounts but continues to run at mounted speed.

**Expected behaviour**: Koltira Deathweaver should stay on his mount. 

**Revision**: 1036

**Comment by Cold-Martijn** [comment] 2022-04-08 11:52
Might be knockback that caused this? Does not usually happen (tested 3 times, could not reproduce).

**Comment by Wolffenstein** [comment] 2022-04-10 05:39
Fixed in rev 1041.

**Closed by Wolffenstein** 2022-04-10 05:39 UTC
