### ISSUE TITLE
Unable to leave rdf queue after starting search for missing slots

### ISSUE THREAD

**Issue by Majst** [Stormforge-gg/Bugtracker-Wotlk-Beta#60] opened 2022-04-08 22:14 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When someone leaves your rdf party and you requeue to fill the spot, you are unable to leave the queue even as party leader.
**Current behaviour**:
The leave queue button does nothing and stuck in queue. 
**Expected behaviour**: 
To be able to leave queue and have the rdf tab change to the different screen where it asks if you would like find players for the missing spot.
**Revision**:

**Comment by Wolffenstein** [comment] 2022-04-08 22:30
Cannot reproduce, works fine for me on local

**Comment by Wolffenstein** [comment] 2022-04-09 01:01
Perhaps fixed in revision 1039.

**Closed by Wolffenstein** 2022-04-09 01:01 UTC
