### ISSUE TITLE
[Quest] The Light of Dawn

### ISSUE THREAD

**Issue by kelsul** [Stormforge-gg/Bugtracker-Wotlk-Beta#22] opened 2022-04-08 10:23 UTC
**Description**: In DK starting zone the quest The Light of Dawn has some visual bugs, such as the DK named NPCs not being trapped by the light correctly when Tirion Fordring appears. 

**Current behaviour**: Visual bugs including: giants running ahead at fast speed, DK named NPCs not being affected by the light correctly when Tirion appears (either not affected at all, or the light orbs jitter around rather than flowing smoothly), Koltira and Thassarian staying mounted throughout the whole event. 

**Expected behaviour**: Should be smooth experience, UD army moves out together, when Tirion appears some NPCs should be getting trapped by light orbs, and Koltira and Thassarian should be dismounted and kneeling after Tirion appears. 

**Revision**: 1036

**Comment by Cold-Martijn** [comment] 2022-04-08 15:07
- giants running ahead at fast speed,
This is actually not a bug, or it is bugged on retail aswell at this moment.

**Comment by Wolffenstein** [comment] 2022-05-10 14:12
Fixed in rev 1139.

**Closed by Wolffenstein** 2022-05-10 14:12 UTC
