### ISSUE TITLE
[NPC][Hellfire Peninsula] Bleeding Hollow Tormentor - Multiple Issues

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Wotlk-Beta#582] opened 2022-05-19 22:22 UTC
**Description**: 
 [Bleeding Hollow Tormentor](https://tbc.wowhead.com/npc=19424/bleeding-hollow-tormentor#abilities) casts fear and can summon a pet, Bleeding Hollow Riding Worg.

**Current behaviour**: 
 Bleeding Hollow Tormentor casts fear ON HIMSELF (lol!)
 Bleeding Hollow Tormentor never casts [Mend Pet](https://tbc.wowhead.com/spell=33976/mend-pet)
 Bleeding Hollow Riding Worg does not despawn if the tormentor resets combat.

**Expected behaviour**:  
 Bleeding Hollow Tormentor casts fear on someone who is NOT 1st in threat table.
 Bleeding Hollow Tormentor casts Mend Pet when pet has low hp.
 Bleeding Hollow Riding Worg despawns when tormentor resets combat.

**Revision**:  
 1217

https://tbc.wowhead.com/npc=19424/bleeding-hollow-tormentor#abilities

![image](https://user-images.githubusercontent.com/105084838/169414256-09be1cb4-a2e7-44ca-8b79-1c01165835b6.png)

**Comment by Cold-Martijn** [comment] 2022-05-20 12:13
I can't fix this one... It is caused by the wrong fear spell ID (WoWhead also links wrong spell) and I don't know what the correct spell is. I don't have data on this, perhaps someone can look into the ATS database for correct ability.

**Comment by Wolffenstein** [comment] 2022-05-23 21:20
Fixed in rev 1241.

**Closed by Wolffenstein** 2022-05-23 21:20 UTC
Labels: CONFIRMED BUG, help wanted
