### ISSUE TITLE
[Quest] On Ruby Wings [Zone] Dragonblight

### ISSUE THREAD

**Issue by Ojren** [Stormforge-gg/Bugtracker-Wotlk-Beta#277] opened 2022-04-25 00:39 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: [Quest](https://www.wowhead.com/quest=12498/on-ruby-wings) Several bugs after latest fix

**Current behaviour**:
1. NPC [Grand Necrolord Antiok](https://www.wowhead.com/npc=28006/grand-necrolord-antiok) sometimes is not spawning on his mount [Thiassi the Lightning Bringer]( https://www.wowhead.com/npc=28018/thiassi-the-lightning-bringer). Killed him several times and sometimes he spawns without Antiok, or Antiok dissapears without triggering script of killing your dragon.
2. After Antiok kills your Wyrmrest Vanquisher player and body of Wyrmrest Vanquisher are sometimes stuck in falling animation with permanent parachute buff(could not reliably repeat, but got that few times).
3. [Rotting Storm Giant](https://www.wowhead.com/npc=27270/rotting-storm-giant#drops) that are guarding quest zone are not using their [Forged Thunder](https://www.wowhead.com/spell=50405/forged-thunder) on flying targets and evade
4. [Flame Fury](https://www.wowhead.com/spell=50348/flame-fury#used-by-npc) ability of [Wyrmrest Vanquisher](https://www.wowhead.com/npc=27996/wyrmrest-vanquisher#abilities) is only working while targeting [Wastes Scavenger](https://www.wowhead.com/npc=28005/wastes-scavenger#models) and fails after channeling if targeting anything else.
5. [Grand Necrolord Antiok](https://www.wowhead.com/npc=28006/grand-necrolord-antiok) is not using his abilities when fighting(just melee)
6.  If logged out while riding [Wyrmrest Vanquisher](https://www.wowhead.com/npc=27996/wyrmrest-vanquisher#abilities) then when you login it will dissapear(considering its fly mount and local geography player will die)

**Expected behaviour**: 

4.It should work in cone without targeting anyone.
5. He should use his aoe fear ability if target in range then use shadow bolts

**Revision**:

**Comment by Wolffenstein** [comment] 2022-04-25 11:17
6. Is not a bug, that's just how vehicles work.

**Comment by Wolffenstein** [comment] 2022-04-25 13:15
2. Can't really reproduce, dunno.

**Comment by Wolffenstein** [comment] 2022-04-25 13:23
Rest fixed in rev 1078.

**Closed by Wolffenstein** 2022-04-25 13:23 UTC
