### ISSUE TITLE
[Spell] Oculus: Amber Drake

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#349] opened 2022-05-07 23:32 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
When using Temporal Rift, the player should get 1 stack of the charge debuff on the boss for every 15,000 damage done.

So, if I hit him for 150000 damage while another amber drake is channeling, they should instantly receive 10 stacks. But it appears that is not happening. I think people are getting 1 stack per attack on the boss?

Also, the increased damage effect (the target of the channeling takes 100% increased damage) should not stack with other drakes, but currently it does. So if 2 amber drakes are channeling on the boss, everyone else is doing 200% extra damage instead of 100%.

**Comment by Wolffenstein** [comment] 2022-05-09 16:23
Stacking damage is not a bug

**Comment by Vishiswaz** [comment] 2022-05-09 16:26
According to my friend who looked it up while we were testing, yes it is a bug. I will ask them to send me the evidence.

**Comment by Wolffenstein** [comment] 2022-05-09 16:34
We researched it during alpha testing and concluded it was not a bug

**Comment by Vishiswaz** [comment] 2022-05-09 16:40
I'll see what my friend can send me and I'll pass it along if it's worth anything.

**Comment by Wolffenstein** [comment] 2022-05-09 17:28
Fixed in rev 1136.

**Closed by Wolffenstein** 2022-05-09 17:28 UTC
