### ISSUE TITLE
[NPC] Gundrak: Gal'darah

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#322] opened 2022-05-07 02:57 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
5 issues:

1. Gal'darah, when in rhino form, does a sort of thunder clap, but the animation does not happen where he's at, at least if he's moving at the time, which he usually is since it happens after he kicks back his target and then chases after them

https://youtu.be/nYGkUYCOtAQ

2. It appears the timing is off between the impale and the rhino form expiring, as players can get stuck above him in mid-air while he's in humanoid form.

https://youtu.be/lVnUtoqjgrg

3. Impale sometimes causes a visual bug where it doesn't appear that the target has moved, but on their side they see themselves on the rhino horn.

https://youtu.be/QQN5AwVELKQ

4. Hand of Freedom and possibly Hand of Protection should be able to free someone from impale, according to this wowhead comment from 2008 https://www.wowhead.com/npc=29306/galdarah#comments:id=522423

5. Puncture doesn't seem to be happening, at all, ever.

**Comment by Wolffenstein** [comment] 2022-05-07 21:44
1. Is clientside and can't be fixed

**Comment by Vishiswaz** [comment] 2022-05-07 21:45
I've never seen it that way on other servers. But alright!

**Comment by NatsumeLily** [comment] 2022-05-08 01:55
He should not be immune to Disarm.

**Comment by Wolffenstein** [comment] 2022-06-03 00:59
cant reproduce 3

**Comment by Wolffenstein** [comment] 2022-06-03 02:47
Fixed in rev 1376.

**Closed by Wolffenstein** 2022-06-03 02:47 UTC
Labels: CONFIRMED BUG, npc, dungeon
