### ISSUE TITLE
[Zone] UP; [NPC] Gortok Palehoof (26687) Missing Ability

### ISSUE THREAD

**Issue by Dirtsleeper** [Stormforge-gg/Bugtracker-Wotlk-Beta#244] opened 2022-04-16 02:07 UTC
**Current behaviour**:
He never casts [Spell] Arcing Smash (28168)

**Expected behaviour**: 
He casts [Spell] Arcing Smash (28168)

**Revision**: 
1048

**Comment by Lmdezorn** [comment] 2022-04-16 08:28
I can't reproduce the issue you're reporting: Gortok casts regularly Arcing Smash (the spellID is 48260). Did you try with only one char or several? Since it's a frontal cone ability, maybe he needs to have more than 1 opponent to decide to cast it?

![image](https://user-images.githubusercontent.com/59399784/163668141-3bd19d0d-2eef-4b83-b2a9-51329714f32d.png)

**Comment by Dirtsleeper** [comment] 2022-04-19 13:52
Tried with a single character. I imagine it should cast regardless of enemy count.

**Comment by Wolffenstein** [comment] 2022-04-20 15:12
Should be fixed in rev 1059.

**Closed by Wolffenstein** 2022-04-20 15:12 UTC
