### ISSUE TITLE
[NPC] (Multiple) Aggro radius

### ISSUE THREAD

**Issue by kgms20** [Stormforge-gg/Bugtracker-Wotlk-Beta#157] opened 2022-04-11 17:57 UTC
**Description**: 
Multiple npc's across multiple zones in Northrend.
https://wowpedia.fandom.com/wiki/Aggro_radius
**Current behaviour**:
Aggro radius seems either extremelly low or does not scale with the players level.
Tested on different mobs and levels in all zones in Northrend + rares.
https://streamable.com/il8oxw
**Expected behaviour**: 
Every mob should have appropriate aggro range for its level and the aggro should react/scale with the players level. 
The aggro radius of a mob having the same level as the player is roughly 20 yards (~ 18 meters)
Aggro radius varies with level difference at a rate of roughly 1 yard/level.
Minimum aggro radius for a mob seems to be combat range (5 yards).
https://wowpedia.fandom.com/wiki/Aggro_radius

**Revision**:

**Comment by Cold-Martijn** [comment] 2022-04-12 09:45
Shadow/KGMS20 - you use Streamable to post videos, which is fine. However, Streamable videos get deleted after some period of time. If the issue is not fixed by then, the videos are gone aswell. Videos are good, would be a shame to lose them... please use youtube or something else that lasts forever 😄

**Comment by Wolffenstein** [comment] 2022-04-13 00:02
Should be better after rev 1046.

**Closed by Wolffenstein** 2022-04-13 00:02 UTC
