### ISSUE TITLE
[NPC][Dungeon] grand-magus-telestra

### ISSUE THREAD

**Issue by Gn0m** [Stormforge-gg/Bugtracker-Wotlk-Beta#53] opened 2022-04-08 20:11 UTC
![image](https://user-images.githubusercontent.com/40593874/162518819-95ab2d91-7b2e-4d67-a420-17b648b26808.png)
https://www.wowhead.com/npc=26731/grand-magus-telestra

**Description**: 

**Current behaviour**: After the phase where the boss splits into 3 copies, he does not go back, the copies die, but the boss in the center does not appear

**Expected behaviour**: After the split phase, the boss must gather back at 1 so the fight can continue.

**Revision**:

**Comment by Nuy** [comment] 2022-04-08 20:23
Hasn't happened to me when I was testing but phase 3 seems to be missing.

"Once the clones are destroyed she will reappear with 50% health, and will use the same attacks as in phase one. When she reaches 25% health, she will Freeze everyone and cast Fireball Volley (AoE fireball spell) that will hit everyone in a 30 yard radius."

https://wowwiki-archive.fandom.com/wiki/Grand_Magus_Telestra

**Comment by Gn0m** [comment] 2022-04-08 20:29
Unfortunately, I don’t remember exactly how much% remained, but she did phase 3, that is, she froze us and threw fireballs. This may have been the second time she's made copies.

**Comment by Gn0m** [comment] 2022-04-08 20:34
it's quite possible that we had little damage and didn't get past 1 clone creation as she decided to create a second time, from your article: "She has been observed to clone at least twice if not taken down quickly."

**Comment by Gn0m** [comment] 2022-04-08 20:54
maybe the problem was in the pet, I had a water elemental after we left constantly in the floor of the bug, the feeling that he was constantly rushing back to attack the boss

**Comment by Lmdezorn** [comment] 2022-04-12 20:40
Got the issue when I first ran Nexus today (dual log, but only 1 char in the dungeon) but I wasn't paying too much attention. Spent the whole evening trying to reproduce the bug, but could only manage to get it once. I have the logs for this try but haven't yet been able to extract what parameters triggered the bug. Here is the logs for that specific try if you need: [Grand Magus Telestra.txt](https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/files/8476397/Grand.Magus.Telestra.txt)

- tried various kill orders
- tried kicking the images just before killing them (on Critter, Time Stop, Ice Barb, Blizzard, Scorch). 

The bug occured when I kicked Scorch on the last image, but I tried it again afterwards without triggering any issue so the trigger seems more complex than that. Moreover, I got the feeling while I was waiting in vain for the boss to reappear that, when I killed the last image on that try (the fire one), the frost and arcane effects at the center of the room had vanished and that only the fire effect was visible.

**Comment by Lmdezorn** [comment] 2022-04-15 20:08
It took me 3 whole evenings of trying to reproduce to finally understand that the trigger wasn't as convoluted as I had thought. Indeed, it would seem that the location where you kill the images impacts the outcome of having Telestra reappearing or not: 
- when every image is killed well within the "runic ring" (the glowing runes on the ground), the encounter goes as planned and Telestra reappears. 
- however, if any of those 3 images dies close to or beyond the edges of the "runic ring", as you can see in the first picture below. The location of the corpse in the SS is around the limit range, and the second picture confirms that it triggers the bug (you can see in my Skada encounter timer that nothing has happened for 30 seconds).

![WoWScrnShot_041522_214832](https://user-images.githubusercontent.com/59399784/163626038-c66fc8d7-4608-4cc6-bf55-f486fcde14eb.jpg)
![WoWScrnShot_041522_214903](https://user-images.githubusercontent.com/59399784/163626068-dbf58ea9-62ef-4d53-91b8-dd53d2d6e135.jpg)

**Step to reproduce the issue**: Engage Grand Magus Telestra (npc=26731) in The Nexus, trigger the P2 by lowering her hp under 50%, then drag one of the images at the edges of the room then kill it there, kill every image and observe that Telestra never reappears.

**Comment by Wolffenstein** [comment] 2022-04-21 16:10
Fixed in rev 1063.

**Closed by Wolffenstein** 2022-04-21 16:10 UTC
