### ISSUE TITLE
Halls of Lightning: Ionar

### ISSUE THREAD

**Issue by Vishiswaz** [Stormforge-gg/Bugtracker-Wotlk-Beta#288] opened 2022-05-04 03:59 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Ionar has a few bugs.

1. He should be splitting at 75%, 50%, and 25% health. Currently he splits more often than that with a group doing slowish damage. I think he split again around 12% for us? Shouldn't be time-based really, it should be based on his health.

Also note that he should be coded to change that in a later patch, I forget which one, where he only splits at 50%. Many other servers just use this version even from the start to make the boss less obnoxious or because they don't know any better. Up to you guys if you wanna go Blizzlike or follow suit. Crystalsong went blizzlike on this and people complained because they're so used to the incorrect version.

_EDIT:
This happened as a hotfix during 3.3 in original blizzard wotlk. https://warcraft.blizzplanet.com/blog/comments/wow_patch_3_3_0_a_recent_in_game_fixes_12_16_09_

2. The sparks are changing aggro in the middle of their movement. This should not happen. Each spark should lock onto its target (I believe evenly distributed amongst the group) and then keep pursuing them until they get called back to where Ionar despawned.

3. After that, a lightning animation happens and Ionar respawns and the sparks disappear. That is correct. But there's a bug on this server where in the time between the lightning and the despawn of the sparks, they start moving towards the group again. This should not happen. They should be immobile until they despawn.

For reference: https://youtu.be/OU8NYyAJCk8

**Comment by BAndysc** [comment] 2022-05-04 10:01
Could you please record a repro video for 1 and 2, because I can't reproduce it, thanks!

**Comment by Vishiswaz** [comment] 2022-05-05 02:46
> Could you please record a repro video for 1 and 2, because I can't reproduce it, thanks!

Here you go

https://youtu.be/fEYlcFYahH0

It appears that for 1, it's happening every 20% instead of every 25%.

And for 2, it happens when the other player shadowmelds or vanishes (probably Feign Death and mage invis too, didn't test)

**Comment by Wolffenstein** [comment] 2022-05-05 12:03
Fixed in rev 1113.

**Closed by Wolffenstein** 2022-05-05 12:03 UTC
