### ISSUE TITLE
[Quest]Bring 'Em Back Alive | [Zone]Borean Thundra

### ISSUE THREAD

**Issue by numbquendera** [Stormforge-gg/Bugtracker-Wotlk-Beta#39] opened 2022-04-08 16:41 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Infinite agro and loose control of your character

**Current behaviour**: The infected kodo beast, when you tame it and pass by a random mob, keeps agroing it and you loose control of your character untill the kodo is killed or you dismount it.

**Expected behaviour**:  Infected kodo should not agro any mobs and not making you loose control of your char.
https://www.wowhead.com/quest=11690/bring-em-back-alive

**Revision**:

**Comment by Evolvee** [comment] 2022-05-08 10:07
was probably caused by a core issue that is now fixed

need retest

**Comment by therealCrysis** [comment] 2022-05-11 11:18
Have you managed to test it once more @numbquendera ?

**Comment by numbquendera** [comment] 2022-05-11 17:13
Still not fixed

**Comment by Cold-Martijn** [comment] 2022-05-13 08:55
Fixed soon(tm) fix needs to be uploaded.

**Closed by Cold-Martijn** 2022-05-13 08:55 UTC
Labels: question, quest, npc, core
