### ISSUE TITLE
[Quest][Stormwind] Fate, Up Against Your Will, Jaina doesn't spawn (id 13369)

### ISSUE THREAD

**Issue by CosminPOP** [Stormforge-gg/Bugtracker-Wotlk-Beta#285] opened 2022-04-29 20:26 UTC
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: 
Quest says: speak to jaina when you are ready to leave but Jaina is not there
**Current behaviour**:
Jaina doesnt spawn on quest accept.
**Expected behaviour**: 
Jaina should spawn and teleport you to Org.
**Revision**: 
1090

**Comment by Cold-Martijn** [comment] 2022-04-30 08:56
Duplicate of https://github.com/Stormforge-gg/Bugtracker-Wotlk-Beta/issues/278

**Closed by Cold-Martijn** 2022-04-30 08:56 UTC
